//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheMorningApp.ServiceReferenceLocalMain {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceLocalMain.WebServiceLocalMainSoap")]
    public interface WebServiceLocalMainSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        TheMorningApp.ServiceReferenceLocalMain.HelloWorldResponse HelloWorld(TheMorningApp.ServiceReferenceLocalMain.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<TheMorningApp.ServiceReferenceLocalMain.HelloWorldResponse> HelloWorldAsync(TheMorningApp.ServiceReferenceLocalMain.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public TheMorningApp.ServiceReferenceLocalMain.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(TheMorningApp.ServiceReferenceLocalMain.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public TheMorningApp.ServiceReferenceLocalMain.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(TheMorningApp.ServiceReferenceLocalMain.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceLocalMainSoapChannel : TheMorningApp.ServiceReferenceLocalMain.WebServiceLocalMainSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceLocalMainSoapClient : System.ServiceModel.ClientBase<TheMorningApp.ServiceReferenceLocalMain.WebServiceLocalMainSoap>, TheMorningApp.ServiceReferenceLocalMain.WebServiceLocalMainSoap {
        
        public WebServiceLocalMainSoapClient() {
        }
        
        public WebServiceLocalMainSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceLocalMainSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceLocalMainSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceLocalMainSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TheMorningApp.ServiceReferenceLocalMain.HelloWorldResponse TheMorningApp.ServiceReferenceLocalMain.WebServiceLocalMainSoap.HelloWorld(TheMorningApp.ServiceReferenceLocalMain.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            TheMorningApp.ServiceReferenceLocalMain.HelloWorldRequest inValue = new TheMorningApp.ServiceReferenceLocalMain.HelloWorldRequest();
            inValue.Body = new TheMorningApp.ServiceReferenceLocalMain.HelloWorldRequestBody();
            TheMorningApp.ServiceReferenceLocalMain.HelloWorldResponse retVal = ((TheMorningApp.ServiceReferenceLocalMain.WebServiceLocalMainSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TheMorningApp.ServiceReferenceLocalMain.HelloWorldResponse> TheMorningApp.ServiceReferenceLocalMain.WebServiceLocalMainSoap.HelloWorldAsync(TheMorningApp.ServiceReferenceLocalMain.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<TheMorningApp.ServiceReferenceLocalMain.HelloWorldResponse> HelloWorldAsync() {
            TheMorningApp.ServiceReferenceLocalMain.HelloWorldRequest inValue = new TheMorningApp.ServiceReferenceLocalMain.HelloWorldRequest();
            inValue.Body = new TheMorningApp.ServiceReferenceLocalMain.HelloWorldRequestBody();
            return ((TheMorningApp.ServiceReferenceLocalMain.WebServiceLocalMainSoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
